/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Pasien;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import table.PasienTable;
import control.PasienControl;


public class PasienView extends javax.swing.JFrame {

    /**
     * Creates new form PasienView
     */
    private PasienControl pControl;
    List<Pasien> pList;
    
    String action = null;
    int selectedId = 0;
    
    public PasienView() {
        initComponents();
        setComponents(false);
        setUpdateDeleteBtn(false);
        pControl = new PasienControl();
        showPasien();
    }
    
    public void setComponents(boolean value){
        namaField.setEnabled(value);
        usiaField.setEnabled(value);
        priaRB.setEnabled(value);
        wanitaRB.setEnabled(value);
        telpField.setEnabled(value);
    }
    
    public void setUpdateDeleteBtn(boolean value){
        updateBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        namaField.setText("");
        usiaField.setText("");
        telpField.setText("");
        searchField.setText("");
        jkGrup.clearSelection();
    }
    
    public void showPasien(){
        pasienTable.setModel(pControl.showPasien(""));
    }
    
    public void inputanKosongException () throws InputKosongException{
        if(namaField.getText().isEmpty() || usiaField.getText().isEmpty() || telpField.getText().isEmpty())
        {
            throw new InputKosongException();
        }
        if(priaRB.isSelected() == false && wanitaRB.isSelected() == false)
        {
            throw new InputKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkGrup = new javax.swing.ButtonGroup();
        layarPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        pasienIcon = new javax.swing.JLabel();
        pasienLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        rsLabel = new javax.swing.JLabel();
        rumahSakitIcon = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        namaField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        usiaLabel = new javax.swing.JLabel();
        usiaField = new javax.swing.JTextField();
        telpLabel = new javax.swing.JLabel();
        telpField = new javax.swing.JTextField();
        jkLabel = new javax.swing.JLabel();
        priaRB = new javax.swing.JRadioButton();
        wanitaRB = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pasienTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        layarPanel.setBackground(new java.awt.Color(239, 255, 251));

        sidePanel.setBackground(new java.awt.Color(80, 216, 144));
        sidePanel.setForeground(new java.awt.Color(0, 0, 0));

        pasienIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/users-medical (1).png"))); // NOI18N

        pasienLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        pasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        pasienLabel.setText("Pasien");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pasienLabel)
                    .addComponent(pasienIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(pasienIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasienLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerPanel.setBackground(new java.awt.Color(239, 255, 251));
        containerPanel.setForeground(new java.awt.Color(0, 0, 0));

        headerPanel.setBackground(new java.awt.Color(239, 255, 251));
        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        headerPanel.setForeground(new java.awt.Color(0, 0, 0));

        rsLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        rsLabel.setForeground(new java.awt.Color(0, 0, 0));
        rsLabel.setText("Atma Care");

        rumahSakitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hospital (2).png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rumahSakitIcon)
                .addGap(15, 15, 15))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addComponent(rsLabel)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addComponent(rumahSakitIcon)
                        .addGap(18, 18, 18))))
        );

        contentPanel.setBackground(new java.awt.Color(239, 255, 251));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        contentPanel.setForeground(new java.awt.Color(0, 0, 0));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 152, 122));
        searchBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(236, 168, 30));
        updateBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        namaField.setBackground(new java.awt.Color(255, 255, 255));
        namaField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        namaField.setForeground(new java.awt.Color(0, 0, 0));

        namaLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setText("Nama");

        usiaLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        usiaLabel.setForeground(new java.awt.Color(0, 0, 0));
        usiaLabel.setText("Usia");

        usiaField.setBackground(new java.awt.Color(255, 255, 255));
        usiaField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        usiaField.setForeground(new java.awt.Color(0, 0, 0));

        telpLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        telpLabel.setForeground(new java.awt.Color(0, 0, 0));
        telpLabel.setText("No Telepon");

        telpField.setBackground(new java.awt.Color(255, 255, 255));
        telpField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        telpField.setForeground(new java.awt.Color(0, 0, 0));

        jkLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jkLabel.setForeground(new java.awt.Color(0, 0, 0));
        jkLabel.setText("Jenis Kelamin");

        priaRB.setBackground(new java.awt.Color(255, 255, 255));
        jkGrup.add(priaRB);
        priaRB.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        priaRB.setForeground(new java.awt.Color(0, 0, 0));
        priaRB.setText("Pria");

        jkGrup.add(wanitaRB);
        wanitaRB.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        wanitaRB.setForeground(new java.awt.Color(0, 0, 0));
        wanitaRB.setText("Wanita");
        wanitaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanitaRBActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(79, 152, 202));
        saveBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        pasienTable.setBackground(new java.awt.Color(255, 255, 255));
        pasienTable.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        pasienTable.setForeground(new java.awt.Color(0, 0, 0));
        pasienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pasien", "Nama", "Jenis Kelamin", "Usia", "No Telepon"
            }
        ));
        pasienTable.setShowGrid(true);
        pasienTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasienTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pasienTable);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usiaLabel)
                    .addComponent(usiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLabel)
                            .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                .addComponent(searchField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn))
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telpLabel)
                                .addComponent(telpField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jkLabel)
                                .addGroup(contentPanelLayout.createSequentialGroup()
                                    .addComponent(priaRB)
                                    .addGap(32, 32, 32)
                                    .addComponent(wanitaRB))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                    .addComponent(saveBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(cancelBtn))))))
                .addGap(12, 12, 12))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn)
                            .addComponent(addBtn))
                        .addGap(82, 82, 82)
                        .addComponent(namaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(telpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usiaLabel)
                    .addComponent(jkLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priaRB)
                    .addComponent(wanitaRB))
                .addGap(27, 27, 27)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layarPanelLayout = new javax.swing.GroupLayout(layarPanel);
        layarPanel.setLayout(layarPanelLayout);
        layarPanelLayout.setHorizontalGroup(
            layarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layarPanelLayout.setVerticalGroup(
            layarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        clearText();
        action = "Add";
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        action = "Update";
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                try{
                    pControl.deletePasien(selectedId);
                    clearText();
                    showPasien();
                    setComponents(false);
                    setUpdateDeleteBtn(false);
                }catch(Exception e){
                    System.out.println("Error : " + e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setComponents(false);
        try{
            Pasien p = pControl.searchPasien(Integer.parseInt(searchField.getText()));
            if(p == null){
                clearText();
                setUpdateDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else {
                setUpdateDeleteBtn(true);
                selectedId = Integer.parseInt(searchField.getText());
                namaField.setText(p.getNama());
                usiaField.setText(Integer.toString(p.getUsia()));
                telpField.setText(p.getNo_telepon());
                if(p.getJenis_kelamin().equals("Pria")){
                    priaRB.setSelected(true);  
                }else{
                    wanitaRB.setSelected(true);
                }
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try {  
            inputanKosongException();
        if (action.equals("Add")){
            
            if(priaRB.isSelected()){
                Pasien p = new Pasien (          
                    namaField.getText(),
                    "Pria",
                    Integer.parseInt(usiaField.getText()),
                    telpField.getText());
                pControl.insertPasien(p);
            }else{
                 Pasien p = new Pasien (          
                    namaField.getText(),
                    "Wanita",
                    Integer.parseInt(usiaField.getText()),
                    telpField.getText());
                pControl.insertPasien(p);
            }
        }else if (action.equals("Update")){
            if(priaRB.isSelected()){
                Pasien p = new Pasien (          
                    namaField.getText(),
                    "Pria",
                    Integer.parseInt(usiaField.getText()),
                    telpField.getText());
                pControl.updatePasien(p,selectedId);
            }else{
                 Pasien p = new Pasien (          
                    namaField.getText(),
                    "Wanita",
                    Integer.parseInt(usiaField.getText()),
                    telpField.getText());
                pControl.updatePasien(p,selectedId);
            }
        }
        clearText();
        showPasien();
        setComponents(false);
        setUpdateDeleteBtn(false);
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(this, e2.getMessage());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
          setComponents(false);
          setUpdateDeleteBtn(false);
          clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void pasienTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasienTableMouseClicked
        // TODO add your handling code here:
        setUpdateDeleteBtn(true);
        setComponents(false);
        int clickedRow = pasienTable.getSelectedRow();
        TableModel tableModel = pasienTable.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        namaField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        String jk = tableModel.getValueAt(clickedRow, 2).toString();
        if(jk.equals("Pria")){
            priaRB.setSelected(true);
            
        }else{
            wanitaRB.setSelected(true);
        }
        usiaField.setText(tableModel.getValueAt(clickedRow, 3).toString());
        telpField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        setUpdateDeleteBtn(true);
    }//GEN-LAST:event_pasienTableMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void wanitaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanitaRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wanitaRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jkGrup;
    private javax.swing.JLabel jkLabel;
    private javax.swing.JPanel layarPanel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel pasienIcon;
    private javax.swing.JLabel pasienLabel;
    private javax.swing.JTable pasienTable;
    private javax.swing.JRadioButton priaRB;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JLabel rumahSakitIcon;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField telpField;
    private javax.swing.JLabel telpLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField usiaField;
    private javax.swing.JLabel usiaLabel;
    private javax.swing.JRadioButton wanitaRB;
    // End of variables declaration//GEN-END:variables
}
