/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ObatControl;
import control.PasienControl;
import control.PerawatanControl;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import table.PerawatanTable;
import model.Obat;
import model.Pasien;
import model.Perawatan;

/**
 *
 * @author Gabriel
 */
public class PerawatanView extends javax.swing.JFrame {

    /**
     * Creates new form PerawatanView
     */
    private PerawatanControl pwControl;
    private PasienControl pControl;
    private ObatControl oControl;
    
    
    List<Perawatan> pwList;
    List<Pasien> pList;
    List<Obat> oList;
    
    
    String action = null;
    int selectedId = 0;
    
    public PerawatanView() {
        initComponents();
        setComponents(false);
        setUpdateDeleteBtn(false);
        pControl = new PasienControl();
        oControl = new ObatControl();
        pwControl = new PerawatanControl();
        setPasienDropDown();
        setObatDropDown();
        showPerawatan();
    }
    
    public void setComponents(boolean value){
        pasienComboBox.setEnabled(value);
        obatComboBox.setEnabled(value);
        jenisPerawatanField.setEnabled(value);
        durasiField.setEnabled(value);
        statusField.setEnabled(value);
    }
    
    public void setPasienDropDown(){
        pList = pControl.showAllPasien();
        for(int i=0;i<pList.size();i++){
            pasienComboBox.addItem(pList.get(i));
        }
    }
    
    public void setObatDropDown(){
        oList = oControl.showAllObat();
        for(int i=0;i<oList.size();i++){
            obatComboBox.addItem(oList.get(i));
        }
    }
    
    public void setUpdateDeleteBtn(boolean value){
        updateBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        pasienComboBox.setSelectedItem(ABORT);
        obatComboBox.setSelectedItem(ABORT);
        jenisPerawatanField.setText("");
        searchField.setText("");
        durasiField.setText("");
        statusField.setText("");
    }
    
    public void showPerawatan(){
        perawatanTable.setModel(pwControl.showPerawatan(""));
    }
    
    public void inputanKosongException () throws InputKosongException{
        if(pasienComboBox.getSelectedIndex() == -1 || obatComboBox.getSelectedIndex() == -1 || jenisPerawatanField.getText().isEmpty() || durasiField.getText().isEmpty()|| statusField.getText().isEmpty())
        {
            throw new InputKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        arrowLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rsLabel = new javax.swing.JLabel();
        headerPanel2 = new javax.swing.JPanel();
        perawatanLabel = new javax.swing.JLabel();
        headerPanel3 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jenisPerawatanLabel = new javax.swing.JLabel();
        durasiField = new javax.swing.JTextField();
        durasiLabel = new javax.swing.JLabel();
        jenisPerawatanField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        perawatanTable = new javax.swing.JTable();
        obatComboBox = new javax.swing.JComboBox<>();
        pasienLabel = new javax.swing.JLabel();
        obatLabel = new javax.swing.JLabel();
        pasienComboBox = new javax.swing.JComboBox<>();
        statusField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerPanel.setBackground(new java.awt.Color(239, 255, 251));

        headerPanel.setBackground(new java.awt.Color(80, 216, 144));
        headerPanel.setPreferredSize(new java.awt.Dimension(246, 100));

        arrowLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow.png"))); // NOI18N
        arrowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowLabelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hospital (2).png"))); // NOI18N

        rsLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        rsLabel.setForeground(new java.awt.Color(0, 0, 0));
        rsLabel.setText("Atma Care");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(arrowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rsLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(arrowLabel))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rsLabel)
                .addGap(29, 29, 29))
        );

        headerPanel2.setBackground(new java.awt.Color(239, 255, 251));
        headerPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        perawatanLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        perawatanLabel.setForeground(new java.awt.Color(0, 0, 0));
        perawatanLabel.setText("Perawatan");

        javax.swing.GroupLayout headerPanel2Layout = new javax.swing.GroupLayout(headerPanel2);
        headerPanel2.setLayout(headerPanel2Layout);
        headerPanel2Layout.setHorizontalGroup(
            headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(perawatanLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        headerPanel2Layout.setVerticalGroup(
            headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(perawatanLabel)
                .addGap(36, 36, 36))
        );

        headerPanel3.setBackground(new java.awt.Color(239, 255, 251));
        headerPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(236, 168, 30));
        updateBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 152, 122));
        searchBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanel3Layout = new javax.swing.GroupLayout(headerPanel3);
        headerPanel3.setLayout(headerPanel3Layout);
        headerPanel3Layout.setHorizontalGroup(
            headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addGap(30, 30, 30))
        );
        headerPanel3Layout.setVerticalGroup(
            headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(10, 10, 10)
                .addComponent(updateBtn)
                .addContainerGap())
        );

        jenisPerawatanLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jenisPerawatanLabel.setForeground(new java.awt.Color(0, 0, 0));
        jenisPerawatanLabel.setText("Jenis Perawatan");

        durasiField.setBackground(new java.awt.Color(255, 255, 255));
        durasiField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        durasiField.setForeground(new java.awt.Color(0, 0, 0));
        durasiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durasiFieldActionPerformed(evt);
            }
        });

        durasiLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        durasiLabel.setForeground(new java.awt.Color(0, 0, 0));
        durasiLabel.setText("Durasi");

        jenisPerawatanField.setBackground(new java.awt.Color(255, 255, 255));
        jenisPerawatanField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jenisPerawatanField.setForeground(new java.awt.Color(0, 0, 0));
        jenisPerawatanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisPerawatanFieldActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(79, 152, 202));
        saveBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        perawatanTable.setBackground(new java.awt.Color(255, 255, 255));
        perawatanTable.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        perawatanTable.setForeground(new java.awt.Color(0, 0, 0));
        perawatanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Perawatan", "Nama Pasien", "Nama Obat", "Dosis Obat", "Durasi Hari", "Jenis Perawatan", "Status"
            }
        ));
        perawatanTable.setShowGrid(true);
        perawatanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perawatanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(perawatanTable);

        obatComboBox.setBackground(new java.awt.Color(255, 255, 255));
        obatComboBox.setForeground(new java.awt.Color(0, 0, 0));
        obatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatComboBoxActionPerformed(evt);
            }
        });

        pasienLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        pasienLabel.setText("Pasien");

        obatLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        obatLabel.setForeground(new java.awt.Color(0, 0, 0));
        obatLabel.setText("Obat");

        pasienComboBox.setBackground(new java.awt.Color(255, 255, 255));
        pasienComboBox.setForeground(new java.awt.Color(0, 0, 0));
        pasienComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienComboBoxActionPerformed(evt);
            }
        });

        statusField.setBackground(new java.awt.Color(255, 255, 255));
        statusField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        statusField.setForeground(new java.awt.Color(0, 0, 0));

        statusLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(0, 0, 0));
        statusLabel.setText("Status");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(headerPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn))
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusLabel)
                                    .addComponent(durasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(obatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obatLabel)))
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisPerawatanLabel)
                                    .addComponent(durasiLabel)
                                    .addComponent(jenisPerawatanField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(196, 196, 196)
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pasienComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(containerPanelLayout.createSequentialGroup()
                                        .addComponent(pasienLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(14, 14, 14))))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(jenisPerawatanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisPerawatanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(durasiLabel)
                        .addGap(6, 6, 6))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pasienLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obatLabel)
                    .addComponent(durasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrowLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLabelMouseClicked
        // TODO add your handling code here:
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_arrowLabelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        clearText();
        action = "Add";
        pasienComboBox.setSelectedIndex(0);
        obatComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        action = "Update";
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                try{
                    pwControl.deletePerawatan(selectedId);
                    clearText();
                    showPerawatan();
                    setComponents(false);
                    setUpdateDeleteBtn(false);
                }catch(Exception e){
                    System.out.println("Error : " + e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setComponents(false);
        try{
            Perawatan pw = pwControl.searchPerawatan(Integer.parseInt(searchField.getText()));
            if(pw == null){
                clearText();
                setUpdateDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else {
                int indexPasien = -1;
                int indexObat = -1;
                setUpdateDeleteBtn(true);
                selectedId = Integer.parseInt(searchField.getText());
                int idPasien = pw.getPasien().getId_pasien();
                for (Pasien p : pList) {
                    if (p.getId_pasien() == idPasien) {
                        indexPasien = pList.indexOf(p);
                    }
                }
                pasienComboBox.setSelectedIndex(indexPasien);
                int idObat = pw.getObat().getId_obat();
                for (Obat o : oList) {
                    if (o.getId_obat() == idObat) {
                        indexObat = oList.indexOf(o);
                    }
                }
                
                jenisPerawatanField.setText(pw.getJenisPerawatan());
                durasiField.setText(Integer.toString(pw.getDurasi()));
                statusField.setText(pw.getStatus());   
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void jenisPerawatanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisPerawatanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisPerawatanFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try {  
             inputanKosongException();
            int selectedIndexPasien = pasienComboBox.getSelectedIndex();
            Pasien p = pList.get(selectedIndexPasien);
            int selectedIndexObat = obatComboBox.getSelectedIndex();
            Obat o  = oList.get(selectedIndexObat);        
        if (action.equals("Add")){
            
                Perawatan pw = new Perawatan (          
                p,
                o,
                jenisPerawatanField.getText(),
                Integer.parseInt(durasiField.getText()),
                statusField.getText());
                
                pwControl.insertPerawatan(pw);
                
        }else if (action.equals("Update")){
                
                Perawatan pw = new Perawatan (          
                p,
                o,
                jenisPerawatanField.getText(),
                Integer.parseInt(durasiField.getText()),
                statusField.getText());
                
                pwControl.updatePerawatan(pw,selectedId);
        }
        
        clearText();
        showPerawatan();
        setComponents(false);
        setUpdateDeleteBtn(false);
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(this, e2.getMessage());
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setComponents(false);
          setUpdateDeleteBtn(false);
          clearText();
       
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void perawatanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perawatanTableMouseClicked
        // TODO add your handling code here
        setUpdateDeleteBtn(true);
        setComponents(false);
        int indexPasien = -1;
        int indexObat = -1;
        
        int clickedRow = perawatanTable.getSelectedRow();
        TableModel tableModel = perawatanTable.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        int idPasien = Integer.parseInt(tableModel.getValueAt(clickedRow, 7).toString());
        for (Pasien p : pList) {
            if (p.getId_pasien() == idPasien) {
                indexPasien = pList.indexOf(p);
            }
        }
        pasienComboBox.setSelectedIndex(indexPasien);
        int idObat = Integer.parseInt(tableModel.getValueAt(clickedRow,8).toString());
        for (Obat o : oList) {
            if (o.getId_obat() == idObat) {
                indexObat = oList.indexOf(o);
            }
        }
        
        obatComboBox.setSelectedIndex(indexObat);
        jenisPerawatanField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        durasiField.setText(tableModel.getValueAt(clickedRow, 5).toString());
        statusField.setText(tableModel.getValueAt(clickedRow, 6).toString());
        setUpdateDeleteBtn(true);
        
    }//GEN-LAST:event_perawatanTableMouseClicked

    private void pasienComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasienComboBoxActionPerformed

    private void obatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatComboBoxActionPerformed

    private void durasiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durasiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durasiFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerawatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerawatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerawatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerawatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerawatanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel arrowLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField durasiField;
    private javax.swing.JLabel durasiLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JPanel headerPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenisPerawatanField;
    private javax.swing.JLabel jenisPerawatanLabel;
    private javax.swing.JComboBox<Obat> obatComboBox;
    private javax.swing.JLabel obatLabel;
    private javax.swing.JComboBox<Pasien> pasienComboBox;
    private javax.swing.JLabel pasienLabel;
    private javax.swing.JLabel perawatanLabel;
    private javax.swing.JTable perawatanTable;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField statusField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
