/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.RekamMedis;
import model.Pasien;
import model.Dokter;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import control.PasienControl;
import control.DokterControl;
import control.RekamMedisControl;


public class RekamMedisView extends javax.swing.JFrame {

    /**
     * Creates new form PasienView
     */
    private RekamMedisControl rmControl;
    private PasienControl pControl;
    private DokterControl dControl;
    
    
    List<RekamMedis> rmList;
    List<Pasien> pList;
    List<Dokter> dList;
    
    
    String action = null;
    int selectedId = 0;
    
    public RekamMedisView() {
        initComponents();
        setComponents(false);
        setUpdateDeleteBtn(false);
        pControl = new PasienControl();
        dControl = new DokterControl();
        rmControl = new RekamMedisControl();
        setPasienDropDown();
        setDokterDropDown();
        showRekamMedis();
    }
    
    public void setComponents(boolean value){
        pasienComboBox.setEnabled(value);
        dokterComboBox.setEnabled(value);
        diagnosaField.setEnabled(value);
        tanggalField.setEnabled(value);
        totalField.setEnabled(value);
    }
    
    public void setPasienDropDown(){
        pList = pControl.showAllPasien();
        for(int i=0;i<pList.size();i++){
            pasienComboBox.addItem(pList.get(i));
        }
    }
    
    public void setDokterDropDown(){
        dList = dControl.showAllDokter();
        for(int i=0;i<dList.size();i++){
            dokterComboBox.addItem(dList.get(i));
        }
    }
    
    public void setUpdateDeleteBtn(boolean value){
        updateBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        pasienComboBox.setSelectedItem(ABORT);
        dokterComboBox.setSelectedItem(ABORT);
        tanggalField.setText("");
        searchField.setText("");
        diagnosaField.setText("");
        totalField.setText("");
    }
    
    public void showRekamMedis(){
        rekamMedisTable.setModel(rmControl.showRekamMedis(""));
    }
    
    public void inputanKosongException () throws InputKosongException{
        if(pasienComboBox.getSelectedIndex() == -1 || dokterComboBox.getSelectedIndex() == -1 || totalField.getText().isEmpty() || tanggalField.getText().isEmpty() || diagnosaField.getText().isEmpty())
        {
            throw new InputKosongException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkGrup = new javax.swing.ButtonGroup();
        layarPanel = new javax.swing.JPanel();
        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        rsLabel = new javax.swing.JLabel();
        rumahSakitIcon = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        pasienLabel = new javax.swing.JLabel();
        dokterLabel = new javax.swing.JLabel();
        totalBiayaLabel = new javax.swing.JLabel();
        tanggalField = new javax.swing.JTextField();
        tindakanLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rekamMedisTable = new javax.swing.JTable();
        diagnosaField = new javax.swing.JTextField();
        dokterComboBox = new javax.swing.JComboBox<>();
        diagnosaLabel = new javax.swing.JLabel();
        pasienComboBox = new javax.swing.JComboBox<>();
        totalField = new javax.swing.JTextField();
        sidePanel = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        RekamMedisLabel = new javax.swing.JLabel();
        sidePanel1 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        layarPanel.setBackground(new java.awt.Color(239, 255, 251));

        containerPanel.setBackground(new java.awt.Color(239, 255, 251));
        containerPanel.setForeground(new java.awt.Color(0, 0, 0));

        headerPanel.setBackground(new java.awt.Color(239, 255, 251));
        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        headerPanel.setForeground(new java.awt.Color(0, 0, 0));

        rsLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        rsLabel.setForeground(new java.awt.Color(0, 0, 0));
        rsLabel.setText("Atma Care");

        rumahSakitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hospital (2).png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(rsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(rumahSakitIcon)
                .addGap(31, 31, 31))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(rsLabel))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(rumahSakitIcon)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(239, 255, 251));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        contentPanel.setForeground(new java.awt.Color(0, 0, 0));

        pasienLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        pasienLabel.setText("Pasien");

        dokterLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        dokterLabel.setForeground(new java.awt.Color(0, 0, 0));
        dokterLabel.setText("Dokter");

        totalBiayaLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        totalBiayaLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalBiayaLabel.setText("Tanggal");

        tanggalField.setBackground(new java.awt.Color(255, 255, 255));
        tanggalField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        tanggalField.setForeground(new java.awt.Color(0, 0, 0));
        tanggalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalFieldActionPerformed(evt);
            }
        });

        tindakanLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        tindakanLabel.setForeground(new java.awt.Color(0, 0, 0));
        tindakanLabel.setText("Total Biaya");

        saveBtn.setBackground(new java.awt.Color(79, 152, 202));
        saveBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        rekamMedisTable.setBackground(new java.awt.Color(255, 255, 255));
        rekamMedisTable.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        rekamMedisTable.setForeground(new java.awt.Color(0, 0, 0));
        rekamMedisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Rekam Medis", "Pasien", "Dokter", "Diagnosa", "Tanggal", "Total Biaya"
            }
        ));
        rekamMedisTable.setShowGrid(true);
        rekamMedisTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rekamMedisTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rekamMedisTable);

        diagnosaField.setBackground(new java.awt.Color(255, 255, 255));
        diagnosaField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        diagnosaField.setForeground(new java.awt.Color(0, 0, 0));

        dokterComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dokterComboBox.setMinimumSize(new java.awt.Dimension(64, 21));
        dokterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterComboBoxActionPerformed(evt);
            }
        });

        diagnosaLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        diagnosaLabel.setForeground(new java.awt.Color(0, 0, 0));
        diagnosaLabel.setText("Diagnosa");

        pasienComboBox.setBackground(new java.awt.Color(255, 255, 255));
        pasienComboBox.setMinimumSize(new java.awt.Dimension(64, 21));
        pasienComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienComboBoxActionPerformed(evt);
            }
        });

        totalField.setBackground(new java.awt.Color(255, 255, 255));
        totalField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        totalField.setForeground(new java.awt.Color(0, 0, 0));
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(53, 53, 53)
                .addComponent(cancelBtn)
                .addGap(44, 44, 44))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pasienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasienLabel)
                            .addComponent(dokterLabel)
                            .addComponent(diagnosaLabel)
                            .addComponent(diagnosaField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tindakanLabel)
                            .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalBiayaLabel))
                        .addGap(22, 22, 22))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(pasienLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(dokterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dokterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(totalBiayaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosaLabel)
                    .addComponent(tindakanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePanel.setBackground(new java.awt.Color(80, 216, 144));
        sidePanel.setForeground(new java.awt.Color(0, 0, 0));

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        RekamMedisLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        RekamMedisLabel.setForeground(new java.awt.Color(0, 0, 0));
        RekamMedisLabel.setText("Rekam Medis");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backLabel)
                .addGap(148, 148, 148)
                .addComponent(RekamMedisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RekamMedisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backLabel))
                .addGap(22, 22, 22))
        );

        sidePanel1.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        sidePanel1.setForeground(new java.awt.Color(0, 0, 0));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 152, 122));
        searchBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(236, 168, 30));
        updateBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanel1Layout = new javax.swing.GroupLayout(sidePanel1);
        sidePanel1.setLayout(sidePanel1Layout);
        sidePanel1Layout.setHorizontalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn)
                .addGap(18, 18, 18))
        );
        sidePanel1Layout.setVerticalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layarPanelLayout = new javax.swing.GroupLayout(layarPanel);
        layarPanel.setLayout(layarPanelLayout);
        layarPanelLayout.setHorizontalGroup(
            layarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layarPanelLayout.setVerticalGroup(
            layarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        clearText();
        action = "Add";
        pasienComboBox.setSelectedIndex(0);
        dokterComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        action = "Update";
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                try{
                    rmControl.deleteRekamMedis(selectedId);
                    clearText();
                    showRekamMedis();
                    setComponents(false);
                    setUpdateDeleteBtn(false);
                }catch(Exception e){
                    System.out.println("Error : " + e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setComponents(false);
        try{
            RekamMedis rm = rmControl.searchRekamMedis(Integer.parseInt(searchField.getText()));
            if(rm == null){
                clearText();
                setUpdateDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else {
                int indexPasien = -1;
                int indexDokter = -1;
                setUpdateDeleteBtn(true);
                selectedId = Integer.parseInt(searchField.getText());
                int idPasien = rm.getPasien().getId_pasien();
                for (Pasien p : pList) {
                    if (p.getId_pasien() == idPasien) {
                        indexPasien = pList.indexOf(p);
                    }
                }
                pasienComboBox.setSelectedIndex(indexPasien);
                String idDokter = rm.getDokter().getId_dokter();
                for (Dokter d : dList) {
                    if (d.getId_dokter().equals(idDokter)) {
                        indexDokter = dList.indexOf(d);
                    }
                }
                dokterComboBox.setSelectedIndex(indexDokter);
                diagnosaField.setText(rm.getDiagnosa());
                tanggalField.setText(rm.getTanggal());   
                totalField.setText(Double.toString(rm.getTotalBiaya()));   
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try {  
            inputanKosongException();
            int selectedIndexPasien = pasienComboBox.getSelectedIndex();
            Pasien p = pList.get(selectedIndexPasien);
            int selectedIndexDokter = dokterComboBox.getSelectedIndex();
            Dokter d = dList.get(selectedIndexDokter);    
        if (action.equals("Add")){
            
                RekamMedis rm = new RekamMedis (          
                p,
                d,
                diagnosaField.getText(),           
                tanggalField.getText(),
                Double.parseDouble(totalField.getText()));
                
                rmControl.insertRekamMedis(rm);
                
        }else if (action.equals("Update")){
                
                RekamMedis rm = new RekamMedis (          
                p,
                d,
                diagnosaField.getText(),           
                tanggalField.getText(),
                Double.parseDouble(totalField.getText()));
                
                rmControl.updateRekamMedis(rm,selectedId);
        }
        
        clearText();
        showRekamMedis();
        setComponents(false);
        setUpdateDeleteBtn(false);
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(this, e2.getMessage());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
          setComponents(false);
          setUpdateDeleteBtn(false);
          clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void rekamMedisTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rekamMedisTableMouseClicked
        // TODO add your handling code here:
        setUpdateDeleteBtn(true);
        setComponents(false);
        int indexPasien = -1;
        int indexDokter = -1;
        int indexObat = -1;
        
        int clickedRow = rekamMedisTable.getSelectedRow();
        TableModel tableModel = rekamMedisTable.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        int idPasien = Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString());
        for (Pasien p : pList) {
            if (p.getId_pasien() == idPasien) {
                indexPasien = pList.indexOf(p);
            }
        }
        pasienComboBox.setSelectedIndex(indexPasien);
        String idDokter = (tableModel.getValueAt(clickedRow, 7).toString());
        for (Dokter d : dList) {
            if (d.getId_dokter().equals(idDokter)) {
                indexDokter = dList.indexOf(d);
            }
        }
        dokterComboBox.setSelectedIndex(indexDokter);
        diagnosaField.setText(tableModel.getValueAt(clickedRow, 3).toString());
        tanggalField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        totalField.setText(tableModel.getValueAt(clickedRow, 5).toString());
        
        setUpdateDeleteBtn(true);
    }//GEN-LAST:event_rekamMedisTableMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_backLabelMouseClicked

    private void dokterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dokterComboBoxActionPerformed

    private void pasienComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasienComboBoxActionPerformed

    private void tanggalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalFieldActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RekamMedisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RekamMedisLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField diagnosaField;
    private javax.swing.JLabel diagnosaLabel;
    private javax.swing.JComboBox<Dokter> dokterComboBox;
    private javax.swing.JLabel dokterLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jkGrup;
    private javax.swing.JPanel layarPanel;
    private javax.swing.JComboBox<Pasien> pasienComboBox;
    private javax.swing.JLabel pasienLabel;
    private javax.swing.JTable rekamMedisTable;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JLabel rumahSakitIcon;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sidePanel1;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JLabel tindakanLabel;
    private javax.swing.JLabel totalBiayaLabel;
    private javax.swing.JTextField totalField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
