/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Resep;
import model.Pasien;
import model.Dokter;
import model.Obat;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import table.ResepTable;
import control.ResepControl;
import control.PasienControl;
import control.DokterControl;
import control.ObatControl;


public class ResepView extends javax.swing.JFrame {

    /**
     * Creates new form PasienView
     */
    private ResepControl rControl;
    private PasienControl pControl;
    private DokterControl dControl;
    private ObatControl oControl;
    
    
    List<Resep> rList;
    List<Pasien> pList;
    List<Dokter> dList;
    List<Obat> oList;
    
    
    String action = null;
    int selectedId = 0;
    
    public ResepView() {
        initComponents();
        setComponents(false);
        setUpdateDeleteBtn(false);
        pControl = new PasienControl();
        dControl = new DokterControl();
        oControl = new ObatControl();
        rControl = new ResepControl();
        setPasienDropDown();
        setDokterDropDown();
        setObatDropDown();
        showResep();
    }
    
    public void setComponents(boolean value){
        pasienComboBox.setEnabled(value);
        dokterComboBox.setEnabled(value);
        obatComboBox.setEnabled(value);
        tanggalField.setEnabled(value);
        keteranganField.setEnabled(value);
    }
    
    public void setPasienDropDown(){
        pList = pControl.showAllPasien();
        for(int i=0;i<pList.size();i++){
            pasienComboBox.addItem(pList.get(i));
        }
    }
    
    public void setDokterDropDown(){
        dList = dControl.showAllDokter();
        for(int i=0;i<dList.size();i++){
            dokterComboBox.addItem(dList.get(i));
        }
    }
    
    public void setObatDropDown(){
        oList = oControl.showAllObat();
        for(int i=0;i<oList.size();i++){
            obatComboBox.addItem(oList.get(i));
        }
    }
    
    public void setUpdateDeleteBtn(boolean value){
        updateBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        pasienComboBox.setSelectedItem(ABORT);
        dokterComboBox.setSelectedItem(ABORT);
        obatComboBox.setSelectedItem(ABORT);
        tanggalField.setText("");
        searchField.setText("");
        keteranganField.setText("");
    }
    
    public void showResep(){
        resepTable.setModel(rControl.showResep(""));
    }
    
    public void inputanKosongException () throws InputKosongException{
        if(pasienComboBox.getSelectedIndex() == -1 || dokterComboBox.getSelectedIndex() == -1 || obatComboBox.getSelectedIndex() == -1 || tanggalField.getText().isEmpty() || keteranganField.getText().isEmpty())
        {
            throw new InputKosongException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkGrup = new javax.swing.ButtonGroup();
        layarPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        resepIcon = new javax.swing.JLabel();
        resepLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        rsLabel = new javax.swing.JLabel();
        rumahSakitIcon = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        pasienLabel = new javax.swing.JLabel();
        dokterLabel = new javax.swing.JLabel();
        keteranganLabel = new javax.swing.JLabel();
        tanggalField = new javax.swing.JTextField();
        hargaLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resepTable = new javax.swing.JTable();
        keteranganField = new javax.swing.JTextField();
        dokterComboBox = new javax.swing.JComboBox<>();
        obatComboBox = new javax.swing.JComboBox<>();
        obatLabel = new javax.swing.JLabel();
        pasienComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        layarPanel.setBackground(new java.awt.Color(239, 255, 251));

        sidePanel.setBackground(new java.awt.Color(80, 216, 144));
        sidePanel.setForeground(new java.awt.Color(0, 0, 0));

        resepIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/prescription-bottle-alt.png"))); // NOI18N

        resepLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        resepLabel.setForeground(new java.awt.Color(0, 0, 0));
        resepLabel.setText("Resep");

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resepIcon)
                    .addComponent(resepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(backLabel)
                        .addGap(19, 19, 19)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backLabel)
                .addGap(61, 61, 61)
                .addComponent(resepIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resepLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerPanel.setBackground(new java.awt.Color(239, 255, 251));
        containerPanel.setForeground(new java.awt.Color(0, 0, 0));

        headerPanel.setBackground(new java.awt.Color(239, 255, 251));
        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        headerPanel.setForeground(new java.awt.Color(0, 0, 0));

        rsLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        rsLabel.setForeground(new java.awt.Color(0, 0, 0));
        rsLabel.setText("Atma Care");

        rumahSakitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hospital (2).png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rumahSakitIcon)
                .addGap(21, 21, 21))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addComponent(rumahSakitIcon)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addComponent(rsLabel)
                        .addGap(32, 32, 32))))
        );

        contentPanel.setBackground(new java.awt.Color(239, 255, 251));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        contentPanel.setForeground(new java.awt.Color(0, 0, 0));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 152, 122));
        searchBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(236, 168, 30));
        updateBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        pasienLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        pasienLabel.setText("Pasien");

        dokterLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        dokterLabel.setForeground(new java.awt.Color(0, 0, 0));
        dokterLabel.setText("Dokter");

        keteranganLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        keteranganLabel.setForeground(new java.awt.Color(0, 0, 0));
        keteranganLabel.setText("Tanggal");

        tanggalField.setBackground(new java.awt.Color(255, 255, 255));
        tanggalField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        tanggalField.setForeground(new java.awt.Color(0, 0, 0));
        tanggalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalFieldActionPerformed(evt);
            }
        });

        hargaLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        hargaLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaLabel.setText("Keterangan");

        saveBtn.setBackground(new java.awt.Color(79, 152, 202));
        saveBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        resepTable.setBackground(new java.awt.Color(255, 255, 255));
        resepTable.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        resepTable.setForeground(new java.awt.Color(0, 0, 0));
        resepTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Resep", "Pasien", "Dokter", "Obat", "Dosis Obat", "Tanggal", "Keterangan"
            }
        ));
        resepTable.setShowGrid(true);
        resepTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resepTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resepTable);

        keteranganField.setBackground(new java.awt.Color(255, 255, 255));
        keteranganField.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        keteranganField.setForeground(new java.awt.Color(0, 0, 0));

        dokterComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dokterComboBox.setMinimumSize(new java.awt.Dimension(64, 21));
        dokterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterComboBoxActionPerformed(evt);
            }
        });

        obatComboBox.setBackground(new java.awt.Color(255, 255, 255));
        obatComboBox.setMinimumSize(new java.awt.Dimension(64, 21));
        obatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatComboBoxActionPerformed(evt);
            }
        });

        obatLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        obatLabel.setForeground(new java.awt.Color(0, 0, 0));
        obatLabel.setText("Obat");

        pasienComboBox.setBackground(new java.awt.Color(255, 255, 255));
        pasienComboBox.setMinimumSize(new java.awt.Dimension(64, 21));
        pasienComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(pasienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pasienLabel)
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addComponent(addBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(updateBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(deleteBtn))
                                    .addComponent(dokterLabel)
                                    .addComponent(dokterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obatLabel)
                                    .addComponent(obatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                        .addComponent(searchField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBtn))
                                    .addComponent(keteranganField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(keteranganLabel)
                                        .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hargaLabel)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                            .addComponent(saveBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(cancelBtn))))))
                        .addGap(12, 12, 12))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(keteranganLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(hargaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keteranganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(cancelBtn))
                        .addGap(18, 18, 18))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn)
                            .addComponent(addBtn))
                        .addGap(35, 35, 35)
                        .addComponent(pasienLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(dokterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dokterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(obatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layarPanelLayout = new javax.swing.GroupLayout(layarPanel);
        layarPanel.setLayout(layarPanelLayout);
        layarPanelLayout.setHorizontalGroup(
            layarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layarPanelLayout.setVerticalGroup(
            layarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        clearText();
        action = "Add";
        pasienComboBox.setSelectedIndex(0);
        dokterComboBox.setSelectedIndex(0);
        obatComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        action = "Update";
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                try{
                    rControl.deleteResep(selectedId);
                    clearText();
                    showResep();
                    setComponents(false);
                    setUpdateDeleteBtn(false);
                }catch(Exception e){
                    System.out.println("Error : " + e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setComponents(false);
        try{
            Resep r = rControl.searchResep(Integer.parseInt(searchField.getText()));
            if(r == null){
                clearText();
                setUpdateDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else {
                int indexPasien = -1;
                int indexDokter = -1;
                int indexObat = -1;
                setUpdateDeleteBtn(true);
                selectedId = Integer.parseInt(searchField.getText());
                int idPasien = r.getPasien().getId_pasien();
                for (Pasien p : pList) {
                    if (p.getId_pasien() == idPasien) {
                        indexPasien = pList.indexOf(p);
                    }
                }
                pasienComboBox.setSelectedIndex(indexPasien);
                String idDokter = r.getDokter().getId_dokter();
                for (Dokter d : dList) {
                    if (d.getId_dokter().equals(idDokter)) {
                        indexDokter = dList.indexOf(d);
                    }
                }
                dokterComboBox.setSelectedIndex(indexDokter);
                int idObat = r.getObat().getId_obat();
                for (Obat o : oList) {
                    if (o.getId_obat() == idObat) {
                        indexObat = oList.indexOf(o);
                    }
                }
                keteranganField.setText(r.getTanggal());
                tanggalField.setText(r.getKeterangan());   
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try {  
             inputanKosongException();
            int selectedIndexPasien = pasienComboBox.getSelectedIndex();
            Pasien p = pList.get(selectedIndexPasien);
            int selectedIndexDokter = dokterComboBox.getSelectedIndex();
            Dokter d = dList.get(selectedIndexDokter);
            int selectedIndexObat = obatComboBox.getSelectedIndex();
            Obat o  = oList.get(selectedIndexObat);        
        if (action.equals("Add")){
            
                Resep r = new Resep (          
                p,
                d,
                o,
                tanggalField.getText(),
                keteranganField.getText());
                
                rControl.insertResep(r);
                
        }else if (action.equals("Update")){
                
                Resep r = new Resep (          
                p,
                d,
                o,
                tanggalField.getText(),
                keteranganField.getText());
                
                rControl.updateResep(r,selectedId);
        }
        
        clearText();
        showResep();
        setComponents(false);
        setUpdateDeleteBtn(false);
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(this, e2.getMessage());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
          setComponents(false);
          setUpdateDeleteBtn(false);
          clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void resepTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resepTableMouseClicked
        // TODO add your handling code here:
        setUpdateDeleteBtn(true);
        setComponents(false);
        int indexPasien = -1;
        int indexDokter = -1;
        int indexObat = -1;
        
        int clickedRow = resepTable.getSelectedRow();
        TableModel tableModel = resepTable.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        int idPasien = Integer.parseInt(tableModel.getValueAt(clickedRow, 7).toString());
        for (Pasien p : pList) {
            if (p.getId_pasien() == idPasien) {
                indexPasien = pList.indexOf(p);
            }
        }
        pasienComboBox.setSelectedIndex(indexPasien);
        String idDokter = (tableModel.getValueAt(clickedRow, 8).toString());
        for (Dokter d : dList) {
            if (d.getId_dokter().equals(idDokter)) {
                indexDokter = dList.indexOf(d);
            }
        }
        dokterComboBox.setSelectedIndex(indexDokter);
        int idObat = Integer.parseInt(tableModel.getValueAt(clickedRow,9).toString());
        for (Obat o : oList) {
            if (o.getId_obat() == idObat) {
                indexObat = oList.indexOf(o);
            }
        }
        obatComboBox.setSelectedIndex(indexObat);
        tanggalField.setText(tableModel.getValueAt(clickedRow, 5).toString());
        keteranganField.setText(tableModel.getValueAt(clickedRow, 6).toString());
        setUpdateDeleteBtn(true);
    }//GEN-LAST:event_resepTableMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_backLabelMouseClicked

    private void obatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatComboBoxActionPerformed

    private void dokterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dokterComboBoxActionPerformed

    private void pasienComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasienComboBoxActionPerformed

    private void tanggalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<Dokter> dokterComboBox;
    private javax.swing.JLabel dokterLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jkGrup;
    private javax.swing.JTextField keteranganField;
    private javax.swing.JLabel keteranganLabel;
    private javax.swing.JPanel layarPanel;
    private javax.swing.JComboBox<Obat> obatComboBox;
    private javax.swing.JLabel obatLabel;
    private javax.swing.JComboBox<Pasien> pasienComboBox;
    private javax.swing.JLabel pasienLabel;
    private javax.swing.JLabel resepIcon;
    private javax.swing.JLabel resepLabel;
    private javax.swing.JTable resepTable;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JLabel rumahSakitIcon;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
